cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^add-one/(?P<product_id>\d+)/$', views.cart_add_list, name='add-list'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='remove'),
]

flowerflour/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^',include('main.urls', namespace='main')),
    url(r'^menu/',include('menu.urls', namespace='menu')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='order')),
    url(r'^custom-cakes/', include('custom_cakes.urls', namespace='custom-cake')),
    url(r'^clover/', include('clover.urls', namespace='clover')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(regex=r'^$', view=views.home, name='home'),
    url(regex=r'^about/$', view=views.about, name='about'),
    url(regex=r'^delivery/$', view=views.delivery, name='delivery'),
    url(regex=r'^contact/$', view=views.contact, name='contact'),
]

menu/urls.py
from django.conf.urls import url
from menu import views


urlpatterns = [
    url(regex=r'^$', view=views.menu_list, name='list'),
    url(regex=r'^(?P<category_slug>[-\w]+)/$', view=views.menu_list, 
    name='menu_list_by_category'),
    url(regex=r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', view=views.menu_detail, 
    name='menu_detail'),
]

orders/urls.py
from django.conf.urls import url
from orders import views

urlpatterns = [
    url(r'^$', views.order_list, name='list'),
    url(r'^notify/$', views.notify, name='notify'),
    url(r'^custom/$', views.order_custom, name='custom'),
    url(r'^delivery/$', views.order_delivery, name='delivery'),
    url(r'^create/$', views.order_create, name='create')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class CartAddListProductForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from menu.models import Product
from cart.cart import Cart
from cart.forms import CartAddProductForm, CartAddListProductForm
from main.models import Home


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, cd['quantity'], cd['update'])
    return redirect('cart:detail')


@require_POST
def cart_add_list(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddListProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, 1, cd['update'])
    return redirect('menu:list')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def cart_detail(request):
    config = Home.objects.get(id=1)
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'update': True
        })
    return render(request, 'cart/detail.html', {
        'config': config,
        'cart': cart
    })

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} Shopping Cart {% endblock %}

{% block content %}
    <style>
        .theme-inner-banner {
            background: url({{ config.cart_banner_image.url }}) no-repeat center;
            background-size: cover;
            background-attachment: fixed;
            position: relative;
            margin-bottom: 180px;
        }
    </style>
    <div class="theme-inner-banner">
        <div class="opacity">
            <div class="container">
                <h1>Shopping Cart</h1>
                <ul>
                    <li>
                        <a href="{% url 'main:home' %}">Home</a>
                    </li>
                    <li>/</li>
                    <li>Cart</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <h2>Your Shopping Cart</h2>
        <br/>
        <table class="cart">
            <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}
                        {% else %}{% static "images/no_image.png" %}{% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'cart:add' product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }} {{ item.update_quantity_form.update }}
                                <input type="submit" value="Update">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <a href="{% url 'cart:remove' product.id %}">
                                <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                            </a>
                        </td>
                        <td class="num">${{ item.price }}</td>
                        <td class="num">${{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price }}</td>
            </tr>
            </tbody>
        </table>

        <p class="text-right">
            <a href="{% url 'menu:list' %}">
                <button type="submit" class="btn btn-warning">Continue Shopping</button>
            </a>
            <a href="{% url 'order:create' %}">
                <button type="submit" class="btn btn-success">Checkout</button>
            </a>
        </p>
        <br/>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'vendor/jquery.2.2.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
    <script type='text/javascript'
            src='{% static 'vendor/Camera-master/scripts/jquery.mobile.customized.min.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/jquery.easing.1.3.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/camera.min.js' %}'></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap-mega-menu/js/menu.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/Rythm-js/rythm.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/WOW-master/dist/wow.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/owl-carousel/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/fancybox/dist/jquery.fancybox.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/theme.js' %}"></script>
{% endblock %}