cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^add-one/(?P<product_id>\d+)/$', views.cart_add_list, name='add-list'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='remove'),
]

flowerflour/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^',include('main.urls', namespace='main')),
    url(r'^menu/',include('menu.urls', namespace='menu')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='order')),
    url(r'^custom-cakes/', include('custom_cakes.urls', namespace='custom-cake')),
    url(r'^clover/', include('clover.urls', namespace='clover')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(regex=r'^$', view=views.home, name='home'),
    url(regex=r'^about/$', view=views.about, name='about'),
    url(regex=r'^delivery/$', view=views.delivery, name='delivery'),
    url(regex=r'^contact/$', view=views.contact, name='contact'),
]

menu/urls.py
from django.conf.urls import url
from menu import views


urlpatterns = [
    url(regex=r'^$', view=views.menu_list, name='list'),
    url(regex=r'^(?P<category_slug>[-\w]+)/$', view=views.menu_list, 
    name='menu_list_by_category'),
    url(regex=r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', view=views.menu_detail, 
    name='menu_detail'),
]

menu/models.py
from django.db import models
from django.core.urlresolvers import reverse
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django_resized import ResizedImageField
from django.core.files.base import ContentFile
from resizeimage import resizeimage


class Menu(models.Model):
    banner_image = models.ImageField(upload_to='menu')

    class Meta:
        verbose_name = 'menu'

    def __str__(self):
        return "Menu Config"


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menu:menu_list_by_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='products', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, related_name='products')
    sort = models.PositiveIntegerField(default=9999)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menu:menu_detail', args=[self.id, self.slug])

    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     pil_img = Image.open(self.image)
    #     new_image = resizeimage.resize(method='cover', image=pil_img, size=[400, 400])
    #     new_image_io = BytesIO()
    #     new_image.save(new_image_io, format='PNG')
    #     temp_name = self.image.name
    #     self.image.delete(save=False)
    #     self.image.save(
    #         temp_name,
    #         content=ContentFile(new_image_io.getvalue()),
    #         save=False
    #     )
    #     super(Product, self).save()

menu/views.py
from django.shortcuts import render, get_object_or_404
from menu.models import Category, Product
from cart.forms import CartAddListProductForm, CartAddProductForm
from django.contrib import messages
from menu.models import Menu


def menu_list(request, category_slug=None):
    menu = Menu.objects.get(id=1)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by('sort')
    cart_product_form = CartAddListProductForm()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(available=True, category=category).order_by('sort')
    if cart_product_form.is_valid():
        return messages.success(request=request, message='Successfully added item.')
    return render(request=request, template_name='menu/list.html', context={
        'menu': menu,
        'category': category,
        'categories': categories,
        'products': products,
        'category_slug': category_slug,
        'cart_product_form': cart_product_form
    })


def menu_detail(request, id, slug):
    menu = Menu.objects.get(id=1)
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, template_name='menu/detail.html', context={
        'menu': menu,
        'product': product,
        'cart_product_form': cart_product_form
    })

menu/templates/menu/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ product.name }} | Menu{% endblock %}

{% block content %}
    <style>
        .theme-inner-banner {
            background: url({{ menu.banner_image.url }}) no-repeat center;
            background-size: cover;
            background-attachment: fixed;
            position: relative;
            margin-bottom: 180px;
        }
    </style>
    <div class="theme-inner-banner">
        <div class="opacity">
            <div class="container">
                <h1>{{ product.name }}</h1>
                <ul>
                    <li><a href="{% url 'menu:list' %}">Home</a></li>
                    <li>/</li>
                    <li>Menu</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="shop-page shop-details">
        <div class="container">
            <div class="product-details">
                <div class="row">
                    <div class="col-md-5 col-sm-6">
                        <div class="tab-content">
                            <div id="menu0" class="tab-pane fade in active"><img src="{% if product.image %}{{ product.image.url }}
                                {% else %}{% static 'images/no_image.png' %}{% endif %}" alt=""></div>
                        </div>
                    </div>
                    <div class="col-md-7 col-sm-6">
                        <div class="product-info">
                            <h3>{{ product.name }}</h3>
                            <strong>${{ product.price }}</strong>
                            <p>{{ product.description }}</p>
                            <div class="quantity clearfix">
                                <form method="post" action="{% url "cart:add" product.id %}">
                                    {{ cart_product_form }}   
                                    {% csrf_token %}  
                                    <input type="submit" class="cart tran3s p-bg-color" value="ADD TO CART">                               
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'vendor/jquery.2.2.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
<script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/jquery.mobile.customized.min.js' %}'></script>
<script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/jquery.easing.1.3.js' %}'></script>
<script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/camera.min.js' %}'></script>
<script type="text/javascript" src="{% static 'vendor/bootstrap-mega-menu/js/menu.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/Rythm-js/rythm.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/WOW-master/dist/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/owl-carousel/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/fancybox/dist/jquery.fancybox.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/theme.js' %}"></script> 
{% endblock %}

menu/templates/menu/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} Menu {% endblock %}

{% block content %}
    <style>
        .theme-inner-banner {
            background: url({{ menu.banner_image.url }}) no-repeat center;
            background-size: cover;
            background-attachment: fixed;
            position: relative;
            margin-bottom: 180px;
        }
        .shop-page .shop-product-wrapper .single-product h6 a {
            font-size: 18px;
            color: #151515;
            margin-bottom: 10px;
        }
    </style>
    <div class="theme-inner-banner">
        <div class="opacity">
            <div class="container">
                <h1>Our Menu</h1>
                <ul>
                    <li><a href="{% url 'main:home' %}">Home</a></li>
                    <li>/</li>
                    <li>Menu</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="shop-page full-width">
        <div class="row">
            {% if messages.success %}
                {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        Success
                    </div>
                {% endfor %}
            {% endif %}
            <div class="col-lg-9 col-md-8 col-xs-12 float-right">
                <div class="shop-product-wrapper">
                    {% if category_slug %}
                        <h4>{{ category.name|title }}</h4><br/>
                    {% endif %}
                    <div class="row">
                        {% for product in products %}
                            <div class="col-lg-4 col-xs-6">
                                <div class="single-product">
                                    <div class="image">
                                        <a href="{{ product.get_absolute_url }}"><img
                                                src="{% if product.image %}{{ product.image.url }}
                                    {% else %}{% static 'images/no_image.png' %}{% endif %}"></a>
                                    </div>
                                    <h6><a href="{{ product.get_absolute_url }}"
                                           class="tran3s">{{ product.name }}</a></h6>
                                    <strong>${{ product.price }}</strong>
                                    <form method="post" action="{% url "cart:add-list" product.id %}">
                                        {{ cart_product_form }}
                                        {% csrf_token %}
                                        <input type="submit" class="tran3s" value="+">
                                    </form>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% comment %} <ul class="page-pagination">
                    <li class="active"><a href="#" class="tran3s">1</a></li>
                    <li><a href="#" class="tran3s">2</a></li>
                    <li><a href="#" class="tran3s">3</a></li>
                    <li><a href="#" class="tran3s"><i class="flaticon-arrows"></i></a></li>
                </ul> {% endcomment %}
                </div>
            </div>

            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <div class="shop-sidebar">
                    <div class="sidebar-categories">
                        <h3>Categories</h3>
                        <ul>
                            <li class="clearfix"><a href="{% url 'menu:list' %}" class="tran3s">All Products</a></li>
                            {% for category in categories %}
                                <li class="clearfix"><a href="{{ category.get_absolute_url }}"
                                                        class="tran3s">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'vendor/jquery.2.2.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
    <script type='text/javascript'
            src='{% static 'vendor/Camera-master/scripts/jquery.mobile.customized.min.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/jquery.easing.1.3.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/camera.min.js' %}'></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap-mega-menu/js/menu.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/Rythm-js/rythm.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/WOW-master/dist/wow.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/owl-carousel/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/fancybox/dist/jquery.fancybox.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/theme.js' %}"></script>
{% endblock %}