cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^add-one/(?P<product_id>\d+)/$', views.cart_add_list, name='add-list'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='remove'),
]

flowerflour/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^',include('main.urls', namespace='main')),
    url(r'^menu/',include('menu.urls', namespace='menu')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='order')),
    url(r'^custom-cakes/', include('custom_cakes.urls', namespace='custom-cake')),
    url(r'^clover/', include('clover.urls', namespace='clover')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(regex=r'^$', view=views.home, name='home'),
    url(regex=r'^about/$', view=views.about, name='about'),
    url(regex=r'^delivery/$', view=views.delivery, name='delivery'),
    url(regex=r'^contact/$', view=views.contact, name='contact'),
]

menu/urls.py
from django.conf.urls import url
from menu import views


urlpatterns = [
    url(regex=r'^$', view=views.menu_list, name='list'),
    url(regex=r'^(?P<category_slug>[-\w]+)/$', view=views.menu_list, 
    name='menu_list_by_category'),
    url(regex=r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', view=views.menu_detail, 
    name='menu_detail'),
]

orders/urls.py
from django.conf.urls import url
from orders import views

urlpatterns = [
    url(r'^$', views.order_list, name='list'),
    url(r'^notify/$', views.notify, name='notify'),
    url(r'^custom/$', views.order_custom, name='custom'),
    url(r'^delivery/$', views.order_delivery, name='delivery'),
    url(r'^create/$', views.order_create, name='create')
]

main/models.py
from django.db import models
from django.core.validators import validate_email
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.conf import settings


class Profile(models.Model):
    phone = models.CharField(max_length=50)
    user = models.OneToOneField(settings.AUTH_USER_MODEL)

    def __str__(self):
        return 'Profile for {}'.format(self.user)


class Home(models.Model):
    faderimage1 = models.ImageField(upload_to='home')
    faderimage2 = models.ImageField(upload_to='home', blank=True)
    faderimage3 = models.ImageField(upload_to='home', blank=True)
    cake1_image = models.ImageField(upload_to='home', blank=True)
    cake1_title = models.CharField(max_length=50)
    cake1_description = models.CharField(max_length=75)
    cake2_image = models.ImageField(upload_to='home', blank=True)
    cake2_title = models.CharField(max_length=50)
    cake2_description = models.CharField(max_length=75)
    cake3_image = models.ImageField(upload_to='home', blank=True)
    cake3_title = models.CharField(max_length=50)
    cake3_description = models.CharField(max_length=75)
    banner_image = models.ImageField(upload_to='home')
    cart_banner_image = models.ImageField(upload_to='home')

    class Meta:
        verbose_name = 'Home'

    def __str__(self):
        return 'Home Configuration'


class About(models.Model):
    banner_image = models.ImageField(upload_to='about')
    banner_image2 = models.ImageField(upload_to='about')
    mission = models.TextField(max_length=1000)

    class Meta:
        verbose_name = 'About'

    def __str__(self):
        return 'About Configuration'


class Team(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='team')
    description = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Team'

    def __str__(self):
        return self.name


class Review(models.Model):
    name = models.CharField(max_length=100)
    body = models.CharField(max_length=255)
    published = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, validators=[validate_email])
    phone = models.CharField(max_length=35)
    subject = models.CharField(max_length=100, blank=True)
    message = models.TextField(max_length=255, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def send_client_email(self):
        mail = EmailMessage(to=[
            {
                'address': self.email,
                'substitution_data': {
                    'name': self.name,
                    'subject': self.subject,
                    'message': self.message,
                    'phone': self.phone
                }
            }
        ], from_email='contact@flower-flour.com')
        mail.template = 'contact-email'
        mail.send()

    def send_admin_emails(self):
        admins = User.objects.filter(is_superuser=True)
        for admin in admins:
            mail = EmailMessage(to=[
                {
                    'address': admin.email,
                    'substitution_data': {
                        'name': admin.first_name,
                        'client_name': self.name,
                        'subject': self.subject,
                        'message': self.message,
                        'phone': self.phone
                    }
                }
            ], from_email='contact@flower-flour.com')
            mail.template = 'contact-confirm-admin'
            mail.send()

main/forms.py
from django import forms
from main.models import Contact, Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('name', 'body')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'phone', 'subject', 'message')
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': "Name",
            }),
            'email': forms.TextInput(attrs={
                'placeholder': 'Email'
            }),
            'phone': forms.TextInput(attrs={
                'placeholder': 'Phone'
            }),
            'subject': forms.TextInput(attrs={
                'placeholder': 'Subject'
            }),
            'message': forms.Textarea(attrs={
                'placeholder': 'Message'
            })
        }

main/views.py
from django.shortcuts import render
from main.models import Review, Home, About, Team
from main.forms import ContactForm, ReviewForm
from django.core.mail import EmailMessage


def home(request):
    h = Home.objects.get(id=1)
    return render(request=request, template_name='main/home.html', context={'home': h})


def about(request):
    about = About.objects.get(id=1)
    reviews = Review.objects.filter(published=True)
    staff = Team.objects.filter()[0:3]
    return render(request=request, template_name='main/about.html', context={
        'about': about,
        'reviews': reviews,
        'staff': staff
    })


def delivery(request):
    return render(request=request, template_name='main/delivery.html')


def contact(request):
    config = Home.objects.get(id=1)
    if request.method == 'POST':
        form = ContactForm(data=request.POST)
        if form.is_valid():
            c = form.save()
            c.send_client_email()
            c.send_admin_emails()
            return render(request=request, template_name='main/contacted.html', context={
                'config': config,
                'form': form
            })
    else:
        form = ContactForm()
    return render(request=request, template_name='main/contact.html', context={
        'config': config,
        'form': form
    })

main/templates/main/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}About us{% endblock %}

{% block content %}
    <style>
        .theme-inner-banner {
            background: url({{ about.banner_image.url }}) no-repeat center;
            background-size: cover;
            background-attachment: fixed;
            position: relative;
            margin-bottom: 180px;
        }
    </style>
    <div class="theme-inner-banner">
        <div class="opacity">
            <div class="container">
                <h1>About us</h1>
                <ul>
                    <li>
                        <a href="{% url 'main:home' %}">Home</a>
                    </li>
                    <li>/</li>
                    <li>About us</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="about-us-section m-top0">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <div class="row">
                        <div class="col-xs-12">
                            <img src="{% static 'images/cafe2.png' %}" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="text">
                        <h2>Our Mission</h2>
                        <p>{{ about.mission }}</p>
                        <br> <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .short-banner {
            background: url({{ about.banner_image2.url }}) no-repeat center;
            background-size: cover;
            background-attachment: fixed;
        }

    </style>
    <div class="short-banner">
        <div class="opacity">
            <h2>Order your items online & pick them up in store!</h2>
            <a href="{% url 'menu:list' %}" class="theme-button">
                <span>See our menu</span>
            </a>
        </div>
    </div>

    <div class="our-team team-style-two">
        <div class="container">
            <div class="theme-section-title text-center">
                <h2>Our Awesome Team</h2>
                <p>
                    Meet the hands behind the cakes!
                </p>
            </div>
            <div class="row">
                {% for person in staff %}
                    <div class="col-sm-4 col-xs-12">
                        <div class="team-member">
                            <div class="image">
                                <img src="{{ person.image.url }}" alt="">
                            </div>
                            <h5>{{ person.name }}</h5>
                            <p>{{ person.title }}</p>
                            <p>{{ person.description }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="client-section">
        <div class="opacity">
            <div class="container">
                <div class="theme-section-title text-center">
                    <h2>What Our Customers Say</h2>
                    <p></p>
                </div>
                <div class="row">
                    <div id="client-slider">
                        {% for review in reviews %}
                            <div class="item">
                                <div class="client-text">
                                    <i class="flaticon-left-quote icon tran3s"></i>
                                    <p> {{ review.body }}</p>
                                    <h6>{{ review.name }}</h6>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'vendor/jquery.2.2.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
    <script type='text/javascript'
            src='{% static 'vendor/Camera-master/scripts/jquery.mobile.customized.min.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/jquery.easing.1.3.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/camera.min.js' %}'></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap-mega-menu/js/menu.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/Rythm-js/rythm.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/WOW-master/dist/wow.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/owl-carousel/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/fancybox/dist/jquery.fancybox.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/theme.js' %}"></script>
{% endblock %}

main/templates/main/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Contact{% endblock %}


{% block content %}
    <style>
        .theme-inner-banner {
            background: url({{ config.banner_image.url }}) no-repeat center;
            background-size: cover;
            background-attachment: fixed;
            position: relative;
            margin-bottom: 180px;
        }
    </style>
    <div class="theme-inner-banner">
        <div class="opacity">
            <div class="container">
                <h1>Contact Us</h1>
                <ul>
                    <li><a href="{% url 'main:home' %}">Home</a></li>
                    <li>/</li>
                    <li>Contact</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="contact-us">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-xs-12">
                    {% if form.errors %}
                        <div class="alert alert-{{ message.tag }}" role="alert">
                            {{ message|safe }}
                        </div>
                    {% endif %}
                    <div class="contact-us-form">
                        <form class="form-styl-one" method="post">
                            <div class="row">
                                <div class="col-sm-4">
                                    {{ form.name }}
                                </div>
                                <div class="col-sm-4">
                                    {{ form.email }}
                                </div>
                                <div class="col-sm-4">
                                    {{ form.phone }}
                                </div>
                            </div>
                            {{ form.subject }}
                            {{ form.message }}
                            <input type="submit" value="SEND">
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6 col-xs-12">
                    <h4>Hours</h4>
                    <span class="p-color">
                        <b>Monday:</b> Closed <br/>
                        <b>Tuesday - Sunday:</b> 7:30 AM – 5:00 PM<br/>
                        <br/>
                        <br/>
                    </span>
                    <h4>Location</h4>
                    <span class="p-color">
                        896 Willow Street, San Jose,
                        California, 95125
                        <br/>
                        <br/>
                        <br/>
                    </span>
                    <div class="contact-address">
                        <h3>Give us a call today!</h3>
                        <a href="tel:4082790843" class="tran3s">(408) 279-0843</a>
                        <p>Do not hesitate to contact us with any kind of inquiries you may have!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
{% endblock %}


{% block javascript %}
    <script type="text/javascript" src="{% static 'vendor/jquery.2.2.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
    <script type='text/javascript'
            src='{% static 'vendor/Camera-master/scripts/jquery.mobile.customized.min.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/jquery.easing.1.3.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/camera.min.js' %}'></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap-mega-menu/js/menu.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/Rythm-js/rythm.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/WOW-master/dist/wow.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/owl-carousel/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/fancybox/dist/jquery.fancybox.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/jquery.mixitup.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/theme.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/contact-form/validate.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/contact-form/jquery.form.js' %}"></script>
    <script src="{% static 'vendor/sanzzy-map/dist/snazzy-info-window.min.js' %}"></script>
{% endblock %}

main/templates/main/delivery.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Delivery{% endblock %}

{% block content %}
<div class="theme-inner-banner">
    <div class="opacity">
        <div class="container">
            <h1>Delivery</h1>
            <ul>
                <li>
                    <a href="{% url 'main:home' %}">Home</a>
                </li>
                <li>/</li>
                <li>Delivery</li>
            </ul>
        </div>
    </div>
</div>

<div class="delicious-food-section">
        <div class="container">
            <div class="theme-section-title text-center">
                <h2>Delivery</h2>
                <p>
                    Deliver our delicious menu straight to your door using one of the following
                    services enlsited below. If you'd like to <strong>order for pickup</strong>, 
                    please see our menu and checkout through the site.
                </p>
                <br />
                <br />
                <a href="{% url 'menu:list' %}">Our Menu</a>
            </div>
            <div class="row">
                <div class="col-sm-4 col-xs-12">
                    <div class="single-item">
                        <a href="https://www.doordash.com/store/flower-flour-san-jose-224021/" target="_blank">
                            <img src="{% static 'images/ddash.jpg' %}">
                        </a>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <div class="single-item">
                        <a href="https://www.grubhub.com/restaurant/flower-flour-896-willow-st-san-jose/690779" target="_blank">
                            <img src="{% static 'images/ghub.jpg' %}">
                        </a>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <div class="single-item">
                        <a href="https://www.ubereats.com/san-francisco/food-delivery/flower-flour/4ulflRY5ReOTRvtmYOXpNg/" target="_blank">
                            <img src="{% static 'images/ueats.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'vendor/jquery.2.2.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
<script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/jquery.mobile.customized.min.js' %}'></script>
<script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/jquery.easing.1.3.js' %}'></script>
<script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/camera.min.js' %}'></script>
<script type="text/javascript" src="{% static 'vendor/bootstrap-mega-menu/js/menu.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/Rythm-js/rythm.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/WOW-master/dist/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/owl-carousel/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/fancybox/dist/jquery.fancybox.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/theme.js' %}"></script> 
{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Flower Flour | Bakery and Cafe{% endblock %}

{% block content %}
    <div id="theme-main-banner" class="banner-one">
        <div data-src="{{ home.faderimage1.url }}">
            <div class="camera_caption">
                <div class="container text-center">
                    <h3 class="wow fadeInUp animated p-color">Order Online</h3>
                    <h1 class="wow fadeInUp animated" data-wow-delay="0.2s">Order, Deliver, & Build Cakes!</h1>
                    <p class="wow fadeInUp animated" data-wow-delay="0.4s">
                        Have your favorite item ordered online for pickup or delivered to your door!
                    </p>
                    <a href="{% url 'order:list' %}"
                       class="wow fadeInLeft animated banner-button p-bg-color shop-button tran3s"
                       data-wow-delay="0.6s">order</a>
                    <a href="{% url 'menu:list' %}" class="wow fadeInRight animated banner-button explore tran3s"
                       data-wow-delay="0.6s">Menu</a>
                </div>
            </div>
        </div>
        <div data-src="{{ home.faderimage2.url }}">
            <div class="camera_caption">
                <div class="container text-center">
                    <h3 class="wow fadeInUp animated p-color">Morning Pastries</h3>
                    <h1 class="wow fadeInUp animated" data-wow-delay="0.2s">Tasty coffee & croissants</h1>
                    <p class="wow fadeInUp animated" data-wow-delay="0.4s">Baking for 15 years and we're still
                        counting! </p>
                    <a href="{% url 'menu:list' %}"
                       class="wow fadeInLeft animated banner-button p-bg-color shop-button tran3s"
                       data-wow-delay="0.6s">Menu</a>
                    <a href="{% url 'order:delivery' %}" class="wow fadeInRight animated banner-button explore tran3s"
                       data-wow-delay="0.6s">Delivery</a>
                </div>
            </div>
        </div>
        <div data-src="{{ home.faderimage3.url }}">
            <div class="camera_caption">
                <div class="container text-center">
                    <h3 class="wow fadeInUp animated p-color">Party Cakes</h3>
                    <h1 class="wow fadeInUp animated" data-wow-delay="0.2s">Super delicious party cakes</h1>
                    <p class="wow fadeInUp animated" data-wow-delay="0.4s">Order a birthday party cake altered to your
                        specifications. </p>
                    <a href="{% url 'menu:list' %}"
                       class="wow fadeInLeft animated banner-button p-bg-color shop-button tran3s"
                       data-wow-delay="0.6s">Menu</a>
                    <a href="{% url 'menu:list' %}" class="wow fadeInRight animated banner-button explore tran3s"
                       data-wow-delay="0.6s">Build</a>
                </div>
            </div>
        </div>
    </div>
    <div class="delicious-food-section">
        <div class="container">
            <div class="theme-section-title text-center">
                <h2>Our Delicious Cakes</h2>
                <p>Each cake is hand crafted with care and handled delicately to ensure you with perfect cakes!</p>
            </div>
            <div class="row">
                <div class="col-sm-4 col-xs-12">
                    <div class="single-item">
                        <img src="{{ home.cake1_image.url }}">
                        <h5>
                            <a href="{% url 'menu:list' %}">{{ home.cake1_title }}</a>
                        </h5>
                        <p>{{ home.cake1_description }}</p>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <div class="single-item">
                        <img src="{{ home.cake2_image.url }}">
                        <h5>
                            <a href="{% url 'menu:list' %}">{{ home.cake2_title }}</a>
                        </h5>
                        <p>{{ home.cake2_description }}</p>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <div class="single-item">
                        <img src="{{ home.cake3_image.url }}">
                        <h5>
                            <a href="{% url 'menu:list' %}">{{ home.cake3_title }}</a>
                        </h5>
                        <p>{{ home.cake3_description }}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="theme-section-title">
                <h2>See Our Entire Menu</h2>
                <p>
                    Order our entire menu through the site for pickup in-store.
                    Or use a local delivery service such as
                    UberEats, DoorDash, <br/>or GrubHub to order to your doorstep.
                    You can also order a special custom cake for a special event!
                </p>
                <a href="{% url 'menu:list' %}" class="theme-button"><span>Our Menu</span></a>
            </div>
            <a href="https://app.perka.com/start/?merchantUuid=5fb85973-ba3d-4ff5-b53b-9a4a18780356" target="_blank">
                <img src="http://static.perka.com/profile_button_2_orange_2x.png" alt="perka-button"
                     style="width: 182px; height: 36px;">
            </a>
        </div>
        <br/>
    </div>

    <style>
        .short-banner {
            background: url({{ home.banner_image.url }}) no-repeat center;
            background-size: cover;
            background-attachment: fixed;
        }

    </style>
    <div class="short-banner">
        <div class="opacity">
            <h2>Order your items online & pick them up in store!</h2>
            <a href="{% url 'menu:list' %}" class="theme-button">
                <span>See our menu</span>
            </a>
        </div>
    </div>

    <div class="about-us-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <img src="{% static 'images/home/pizza.png' %}" alt="" class="pizza"></div>
                <div class="col-md-6 col-xs-12">
                    <div class="text">
                        <h2>Special Event? Special Cake!</h2>
                        <span class="p-color"> A special event calls for a special cake! Our high-end custom cakes can be picked
                        up from our store or kindly delivered to you on the day (or day prior) of the event! </span>
                        <span> If you'd like to order a custom cake, please use our
                        <a class="tran3s" href="{% url 'order:custom' %}">custom cake form</a>. Here you can build a custom cake and have it ready for your event!
                    We also advise directly contacting us in regards to more specific or elaborate cakes! We want to make sure your cake is perfect!</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'vendor/jquery.2.2.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
    <script type='text/javascript'
            src='{% static 'vendor/Camera-master/scripts/jquery.mobile.customized.min.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/jquery.easing.1.3.js' %}'></script>
    <script type='text/javascript' src='{% static 'vendor/Camera-master/scripts/camera.min.js' %}'></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap-mega-menu/js/menu.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/Rythm-js/rythm.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/WOW-master/dist/wow.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/owl-carousel/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/fancybox/dist/jquery.fancybox.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/theme.js' %}"></script>
{% endblock %}