cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^add-one/(?P<product_id>\d+)/$', views.cart_add_list, name='add-list'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='remove'),
]

flowerflour/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^',include('main.urls', namespace='main')),
    url(r'^menu/',include('menu.urls', namespace='menu')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='order')),
    url(r'^custom-cakes/', include('custom_cakes.urls', namespace='custom-cake')),
    url(r'^clover/', include('clover.urls', namespace='clover')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(regex=r'^$', view=views.home, name='home'),
    url(regex=r'^about/$', view=views.about, name='about'),
    url(regex=r'^delivery/$', view=views.delivery, name='delivery'),
    url(regex=r'^contact/$', view=views.contact, name='contact'),
]

menu/urls.py
from django.conf.urls import url
from menu import views


urlpatterns = [
    url(regex=r'^$', view=views.menu_list, name='list'),
    url(regex=r'^(?P<category_slug>[-\w]+)/$', view=views.menu_list, 
    name='menu_list_by_category'),
    url(regex=r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', view=views.menu_detail, 
    name='menu_detail'),
]

main/models.py
from django.db import models
from django.core.validators import validate_email
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.conf import settings


class Profile(models.Model):
    phone = models.CharField(max_length=50)
    user = models.OneToOneField(settings.AUTH_USER_MODEL)

    def __str__(self):
        return 'Profile for {}'.format(self.user)


class Home(models.Model):
    faderimage1 = models.ImageField(upload_to='home')
    faderimage2 = models.ImageField(upload_to='home', blank=True)
    faderimage3 = models.ImageField(upload_to='home', blank=True)
    cake1_image = models.ImageField(upload_to='home', blank=True)
    cake1_title = models.CharField(max_length=50)
    cake1_description = models.CharField(max_length=75)
    cake2_image = models.ImageField(upload_to='home', blank=True)
    cake2_title = models.CharField(max_length=50)
    cake2_description = models.CharField(max_length=75)
    cake3_image = models.ImageField(upload_to='home', blank=True)
    cake3_title = models.CharField(max_length=50)
    cake3_description = models.CharField(max_length=75)
    banner_image = models.ImageField(upload_to='home')
    cart_banner_image = models.ImageField(upload_to='home')

    class Meta:
        verbose_name = 'Home'

    def __str__(self):
        return 'Home Configuration'


class About(models.Model):
    banner_image = models.ImageField(upload_to='about')
    banner_image2 = models.ImageField(upload_to='about')
    mission = models.TextField(max_length=1000)

    class Meta:
        verbose_name = 'About'

    def __str__(self):
        return 'About Configuration'


class Team(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='team')
    description = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Team'

    def __str__(self):
        return self.name


class Review(models.Model):
    name = models.CharField(max_length=100)
    body = models.CharField(max_length=255)
    published = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, validators=[validate_email])
    phone = models.CharField(max_length=35)
    subject = models.CharField(max_length=100, blank=True)
    message = models.TextField(max_length=255, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def send_client_email(self):
        mail = EmailMessage(to=[
            {
                'address': self.email,
                'substitution_data': {
                    'name': self.name,
                    'subject': self.subject,
                    'message': self.message,
                    'phone': self.phone
                }
            }
        ], from_email='contact@flower-flour.com')
        mail.template = 'contact-email'
        mail.send()

    def send_admin_emails(self):
        admins = User.objects.filter(is_superuser=True)
        for admin in admins:
            mail = EmailMessage(to=[
                {
                    'address': admin.email,
                    'substitution_data': {
                        'name': admin.first_name,
                        'client_name': self.name,
                        'subject': self.subject,
                        'message': self.message,
                        'phone': self.phone
                    }
                }
            ], from_email='contact@flower-flour.com')
            mail.template = 'contact-confirm-admin'
            mail.send()

main/forms.py
from django import forms
from main.models import Contact, Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('name', 'body')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'phone', 'subject', 'message')
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': "Name",
            }),
            'email': forms.TextInput(attrs={
                'placeholder': 'Email'
            }),
            'phone': forms.TextInput(attrs={
                'placeholder': 'Phone'
            }),
            'subject': forms.TextInput(attrs={
                'placeholder': 'Subject'
            }),
            'message': forms.Textarea(attrs={
                'placeholder': 'Message'
            })
        }

main/views.py
from django.shortcuts import render
from main.models import Review, Home, About, Team
from main.forms import ContactForm, ReviewForm
from django.core.mail import EmailMessage


def home(request):
    h = Home.objects.get(id=1)
    return render(request=request, template_name='main/home.html', context={'home': h})


def about(request):
    about = About.objects.get(id=1)
    reviews = Review.objects.filter(published=True)
    staff = Team.objects.filter()[0:3]
    return render(request=request, template_name='main/about.html', context={
        'about': about,
        'reviews': reviews,
        'staff': staff
    })


def delivery(request):
    return render(request=request, template_name='main/delivery.html')


def contact(request):
    config = Home.objects.get(id=1)
    if request.method == 'POST':
        form = ContactForm(data=request.POST)
        if form.is_valid():
            c = form.save()
            c.send_client_email()
            c.send_admin_emails()
            return render(request=request, template_name='main/contacted.html', context={
                'config': config,
                'form': form
            })
    else:
        form = ContactForm()
    return render(request=request, template_name='main/contact.html', context={
        'config': config,
        'form': form
    })

main/templates/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="ut8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Flower Flour</title>
    <link rel="icon" type="image/png" sizes="56x56" href="{% static 'images/fav-icon/icon.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
</head>
<body>
<div class="main-page-wrapper">

    {% include 'navigation.html' %}

    <div id="loader-wrapper">
        <div id="loader"></div>
    </div>

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}

    <button class="scroll-top tran3s">
        <i class="fa fa-angle-up" aria-hidden="true"></i>
    </button>

    {% block javascript %}
    {% endblock %}
</div>
</body>
</html>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());
    gtag('config', 'UA-124325101-1');
</script>

main/templates/footer.html
 {% load staticfiles %}
 
<footer class="theme-main-footer">
    <div class="top-footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-4 col-xs-12 footer-logo">
                    <a href="{% url 'main:home' %}" class="logo">
                        <img src="{% static 'images/logo2M.png' %}" alt="">
                    </a>
                    <p>896 Willow Street, San Jose, California, 95125</p>
                    <a href="tel:4082790843" class="tran3s">(408) 279-0843</a>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-12 footer-list-widget">
                    <h5>Quick Navigation</h5>
                    <ul>
                        <li>
                            <a href="{% url 'main:about' %}" class="tran3s">About Us</a>
                        </li>
                        <li>
                            <a href="{% url 'menu:list' %}" class="tran3s">Our Menu</a>
                        </li>
                        <li>
                            <a href="{% url 'main:delivery' %}" class="tran3s">Order</a>
                        </li>
                        <li>
                            <a href="{% url 'cart:detail' %}" class="tran3s">Your Cart</a>
                        </li>
                        <li>
                            <a href="{% url 'main:contact' %}" class="tran3s">Contact Us</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4 col-xs-12 col-xs-12 subscribe-widget">
                    <div>
                        <h5>Connect With Us</h5>
                        <p>Stay connected with us through social media!</p>
                        <ul>
                            <li>
                                <a href="https://www.facebook.com/AnisCakeDelights/" class="tran3s" target="_blank">
                                    <i class="fa fa-facebook" aria-hidden="true"></i> Facebook</a>
                            </li>
                            <li>
                                <a href="https://www.yelp.com/biz/flower-flour-san-jose" class="tran3s" target="_blank">
                                    <i class="fa fa-yelp" aria-hidden="true"></i> Yelp</a>
                            </li>
                            <li>
                                <a href="https://app.perka.com/start/?merchantUuid=5fb85973-ba3d-4ff5-b53b-9a4a18780356" class="tran3s"
                                    target="_blank">
                                    <i class="fa fa-star-o" aria-hidden="true"></i> Perka</a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/flower_flour_sj/" class="tran3s"
                                    target="_blank">
                                    <i class="fa fa-instagram" aria-hidden="true"></i> Instagram</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom-footer">
        <p>Copyright &copy;2018
            <span class="p-color">Flower-Flour</span>
        </p>
    </div>
</footer>

main/templates/navigation.html
 {% load staticfiles %}

<header class="theme-menu-wrapper theme-main-menu-one">
    <div class="container">
        <div class="header-wrapper">
            <nav class="theme-main-menu-wrapper navbar" id="mega-menu-wrapper">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1"
                        aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <ul class="nav">
                        <li><a href="{% url 'main:home' %}" class="tran3s">Home</a></li>
                        <li><a href="{% url 'main:about' %}" class="tran3s">About</a></li>
                        <li><a href="{% url 'menu:list' %}" class="tran3s">Menu</a></li>
                        <li class="menu-inner-logo rythm pulse1">
                            <a href="{% url 'main:home' %}" class="tran3s">
                                <img src="{% static 'images/Logo-No-Bacground.png' %}" width="180" height="180" alt="FlowerFlour Logo">
                            </a>
                        </li>
                        <li><a href="{% url 'order:list' %}" class="tran3s">Order</a></li>
                        <li><a href="{% url 'custom-cake:list' %}" class="tran3s">Custom Cakes</a></li>                        
                        <li>
                            <a href="{% url 'cart:detail' %}" class="tran3s">
                                {% with total_items=cart|length %}
                                {% if cart|length > 0 %}
                                    Cart [{{ total_items }}]                                
                                {% else %}
                                    Cart [0]
                                {% endif %}
                                {% endwith %}
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="small-device-logo rythm pulse1"></div>
        </div>
    </div>
</header>